### ISSUE TITLE
Turtle graphic missing on Edge browser

### ISSUE THREAD

**Issue by Ed-Price** [sb/smallbasic-editor#14]
The turtle doesn't show on the Microsoft Edge browser. Google Chrome works fine.

**Comment by OmarTawfik** [comment]
@EdPrice-MSFT  Edge and IE have bugs when rendering SVG elements on the web, and multiple posts online mentioned  it 😢

**Comment by alxnull** [comment]
The turtle currently also isn't shown in Firefox browser.

**Comment by nonkit** [comment]
I think Turtle.svg may be something wrong.

**Comment by alxnull** [comment]
I added a fix for Firefox (#54), Edge still isn't working.

**Comment by allisoninman** [comment]
I think the issue is that Edge doesn't support the "animateTransform" (this is referenced in many posts online and [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform#Browser_compatibility)), not that Edge can't render the SVG.[ It also appears that Edge doesn't plan to support it, at least not soon](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/svgsmilanimation/). 

This is preventing both the Turtle and Shapes from animating (shapes just appear at their final destination after the animation duration). I'm exploring other options now using CSS. 

Documenting this research here for future developers and in case someone has animated SVGs and troubleshooted issues in Edge before and can provide insight.

**Comment by Ed-Price** [comment]
It looks like this is no longer an issue with the new Edge, which is powered by the same technology as Chrome.
