### ISSUE TITLE
GraphicsWindow.Title causes syntax error

### ISSUE THREAD

**Issue by Ed-Price** [sb/smallbasic-editor#163]
This code (the GraphicsWindow.Title method):

GraphicsWindow.Title = "Graphics Window"

Causes this error:

"The library member 'GraphicsWindow.Title' was available in older versions only, and has not been made available to this version yet."

This issue is filed to provide SBD parity. Many core workshops and tutorials use this code. Because of the error, you can't run the code.

**Comment by Ed-Price** [comment]
See also the related Issue 113:

https://github.com/sb/smallbasic-editor/issues/113

**Comment by alxnull** [comment]
@EdPrice-MSFT I would try to fix this issue but I'm unsure of the way to go. Instead of just ignoring all statements with `GraphicsWindow.Title` in the code I thought it might be better to emulate some sort of window title, e.g. like this:

![grafik](https://user-images.githubusercontent.com/26907770/94931844-88cc6900-04c8-11eb-94bf-d64ab3658a20.png)

What do you think?
