### ISSUE TITLE
Monaco editor breaking words incorrectly in hovers

### ISSUE THREAD

**Issue by PieterBenjamin** [sb/smallbasic-editor#55]
I notice that in the file `Backend > SmallBasic.utilities > Resources > LibrariesResources.resx`, the xml attribute `xml: space` is used, but I see [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space) that this attribute is depracated and likely unsupported in modern browsers. The same link recommends making use of the [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) CSS attribute. The CSS attribute also seems to be better suited for the values as the current `xml: space` is wrapping the middle of words onto the next line instead of inserting a new line at a whitespace as shown below.
<img width="503" alt="screen shot 2019-02-19 at 8 17 15 pm" src="https://user-images.githubusercontent.com/19309215/53465498-0386f580-3a03-11e9-97aa-c239f0ecdc48.png">
I'd like to try to fix this but I'm not sure where a change would need to be made.

**Comment by OmarTawfik** [comment]
Thanks @PieterBenjamin for taking a look into the project!

So, `*.resx` files are resource files that hold strings (that will be localized). They are not rendered in the product anywhere. They are generated by Visual Studio, and should not be edited by hand. You can read more about it here:
https://docs.microsoft.com/en-us/dotnet/framework/resources/

What you're seeing in the screenshot (hover UI?) is provided by a separate component, monaco editor:
https://github.com/Microsoft/monaco-editor

It is what is generating this hover, and it controls the style and layout of it. Since you're interested in fixing this, I suggest looking up monaco editor, and if there is some setting or style option we can provide so that it breaks words correctly. Let me know if I can provide anything else. Here is where we're initializing the editor:

https://github.com/sb/smallbasic-editor/blob/9f47c13efeefc0d6b7bd00faf9fff8487d56209c/Source/SmallBasic.Client/Interop/MonacoInterop.ts#L22-L36

**Comment by PieterBenjamin** [comment]
@OmarTawfik , thanks so much for the advice! I managed to fix this by adding the following String wrapper method in the class `HoverProvider` located in the file https://github.com/sb/smallbasic-editor/blob/9f47c13efeefc0d6b7bd00faf9fff8487d56209c/Source/SmallBasic.Compiler/Services/HoverProvider.cs#L16-L70

```
private static System.String WrapString(string str)
{
    string wrappedStr = string.Empty;
    string[] tokens = str.Split(' ');
    int currLength = 0;

    for (int i = 0; i < tokens.Length; i++)
     {
        // +1 to account for the space which will be added
        // after the current token.
        currLength += tokens[i].Length +
        ((i < tokens.Length - 1) ? 1 : 0);

        if (currLength >= LINE_LENGTH)
        {
            wrappedStr += "\n";
            currLength = tokens[i].Length;
         }

         wrappedStr += tokens[i];
         if (i < tokens.Length - 1)
         {
            wrappedStr += " ";
         }
     }

     return wrappedStr;
}
```

I made this work using a readonly int at the top of the class (`private static readonly int LINE_LENGTH = 45`). I know hard coding is certainly not ideal style but I wasn't sure how else to get the hover window length (45 is not arbitrary but the length of the lines in the current hoverwindow). If this is a satisfactory way to fix the issue, I'll submit a pull request, but I wanted to make sure you didn't consider this a "hack" first. 

Note: The actual "fixing" part was not writing the method but, in the [HoverProvider.cs class](https://github.com/sb/smallbasic-editor/blob/9f47c13efeefc0d6b7bd00faf9fff8487d56209c/Source/SmallBasic.Compiler/Services/HoverProvider.cs#L16-L70) where I replaced all the `return new[] { *.name, *.Description}` statements with `return new[] { WrapString(*.name), WrapString(*.Description) }`

This change made the output look like this: 
<img width="623" alt="screen shot 2019-03-01 at 8 52 55 am" src="https://user-images.githubusercontent.com/19309215/53653160-84124580-3bff-11e9-9983-4862739bfb6a.png">
which I believe is the desired style

**Comment by OmarTawfik** [comment]
So, I think that fix won't work for all users, as they will be using different displays and text sizes, and it may break in the future if any font/size changes are made.
This is **likely** controlled by a css property in all browsers:
https://www.w3schools.com/cssref/css3_pr_word-break.asp

The problem is I don't know if monaco exposes an API setting/option to set this. I couldn't find it looking online. How about we start by searching for/opening an issue on the monaco repo on GitHub to ask? I'm sure this is a common problem and others might have wanted to do the same.

**Comment by PieterBenjamin** [comment]
I'll try to look into the monaco editor in more detail this weekend. One thing that concerns me is the editor seems to be responsible for all text displayed on the screen - when I changed `fontSize: 18` to `fontSize: 6` in https://github.com/sb/smallbasic-editor/blob/9f47c13efeefc0d6b7bd00faf9fff8487d56209c/Source/SmallBasic.Client/Interop/MonacoInterop.ts#L22-L36 I saw that ALL text in the editing section (hover menu and otherwise) changed to the updated font size. Would a change to how the monaco editor wraps impact what the user is writing as well?

**Comment by OmarTawfik** [comment]
I don't think it should, as the text editing area should reflect only the user code.

**Comment by PieterBenjamin** [comment]
@OmarTawfik I didn't see any relevant issues in the Monaco repo so I opened a [new one](https://github.com/Microsoft/monaco-editor/issues/1344).

**Comment by PieterBenjamin** [comment]
@OmarTawfik No response, but I was able to confirm that the isssue is [with the Monaco editor](https://github.com/Microsoft/monaco-editor/issues/1344#issuecomment-470299386)

**Comment by OmarTawfik** [comment]
Awesome. I saw their reply.
Maybe we can use the suggested fix in here and experiment to see how it goes?

https://github.com/sb/smallbasic-editor/blob/5bd25d24c25c6372da725b17214bdc1a9a472778/Source/SmallBasic.Editor/Components/Toolbox/MonacoEditor.scss#L11-L26

**Comment by PieterBenjamin** [comment]
@OmarTawfik Yup got it to work. Below is a screenshot:
<img width="627" alt="small basic fixed with css" src="https://user-images.githubusercontent.com/19309215/53983477-1a48de80-40cc-11e9-9a34-5faf4dc9a566.png">
Should I submit a PR for this?

Out of curiosity - would you consider this a bug with the Monaco Editor or specified behavior since it can be fixed with CSS? I understand VS code uses the editor, would a fix like this work for VS code as well?

**Comment by OmarTawfik** [comment]
This is great! If it works on all three browsers,  please submit a PR 👍 
Not sure about vscode. It is not a bug per se, because they designed it with this default behavior, as some keywords/libraries are too long to break.
![image](https://user-images.githubusercontent.com/15987992/53985866-972a8700-40d1-11e9-8a6c-dfc4093ef86a.png)

**Comment by PieterBenjamin** [comment]
To be clear - what are the three browsers? Chrome, Firefox and Safari?

**Comment by OmarTawfik** [comment]
Chrome, Firefox, and Edge. I'm not aware of any users using Safari for now.
Note to self: try to see if there is an easy way to write snapshot tests for all browsers 😓

**Comment by PieterBenjamin** [comment]
@OmarTawfik sorry for the delay, it took me a while to get my hands on a Windows computer. I've just confirmed that the CSS fixes the bug across the board so I'll be submitting a pull request.

**Comment by OmarTawfik** [comment]
@PieterBenjamin thanks for working on a fix!
note: this project is a net core application, so you should not need a Windows computer. it will work on all platforms :)
