### ISSUE TITLE
Decision structure:  AND and OR not working. 

### ISSUE THREAD

**Issue by JacquelinePayne** [sb/smallbasic-editor#79]
When trying to incorporate AND and OR decision structure the online Small Basic is crashing.
For example, when running the following the code does not error but the run window freezes.  This works perfectly fine in the application, just not online.

answer = Textwindow.read()
if answer = "a" or answer = "A" Then
    textwindow.write ("TEST")
endif

**Comment by nonkit** [comment]
Hi @JacquelinePayne, I could run your program on [SBO v1.0](http://superbasic-v2.azurewebsites.net/).  If you run your program on [SBO v0.91](https://smallbasic-publicwebsite.azurewebsites.net/Program/Editor.aspx), this problem is already submitted as a known issue 2 at [a TechNet Wiki article](https://social.technet.microsoft.com/wiki/contents/articles/52397.microsoft-small-basic-online-v0-91-known-issues.aspx).
```
answer = TextWindow.Read()
if answer = "a" or answer = "A" Then
TextWindow.Write ("TEST")
endif
```

**Comment by OmarTawfik** [comment]
~~We should be able to fix it here though. I'll look into it when I've some time this week. Thank you for reporting :)~~
Oh, misread @nonkit's comment. Will close as not a bug then.
